services:
  rabbitmq:
    build: .
    ports:
      - "24752:5672"  # AMQP порт
      - "15672:15672" # Web-интерфейс
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data:

